# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('full_address', models.CharField(blank=True, editable=False, max_length=50)),
                ('latitude', models.FloatField(blank=True, editable=False, null=True)),
                ('longitude', models.FloatField(blank=True, editable=False, null=True)),
                ('website', models.CharField(blank=True, max_length=70, null=True)),
                ('facebook', models.CharField(blank=True, max_length=70, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70)),
                ('fname', models.CharField(blank=True, max_length=70, null=True)),
                ('lname', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('favorite_game', models.CharField(blank=True, max_length=70, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='M', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('contact_info', models.CharField(blank=True, max_length=70, null=True)),
                ('game', models.CharField(max_length=70)),
                ('needed_players', models.IntegerField()),
                ('experience_range', models.CharField(default='any', max_length=70)),
                ('date_created', models.DateField(auto_now=True)),
                ('datetime_of_game', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('game_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GameStore')),
                ('interested_players', models.ManyToManyField(to='main.Player')),
            ],
        ),
    ]
