# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gamestore_store_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestore',
            name='store_hours',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
